apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-app
        image: <docker_image:0.0.1>  # Replace with the name of your Docker image
        ports:
        - containerPort: 8000  # Ensure this matches the port your FastAPI app is running on
