apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace:app1
  labels:
    app: fastapi
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-app
        image: container-registry.com/docker_image/bookstore_app:0.0.1 
        ports:
        - containerPort: 8000  
        imagePullPolicy:Always
        Command:
           - ["Python", "main.py"]
        resources:
            requests:
                cpu: 1m
                memory:128M
            limits:
                cpu: 4
                memory: 2Gi
