apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace:app1
  labels:
     app: fastapi-app
     
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5432
  selector:
    app: fastapi-ap
