replicaCount: 2
namespace: test
image:
  repository: container-registry.com/docker_image/bookstore_app
  tag: "0.0.1"
  pullPolicy: Always

service:
  port: 8000

resources:
  limits:
    cpu: "4"
    memory: "2Gi"
  requests:
    cpu: "1m"
    memory: "128M"
